import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "users" ALTER COLUMN "role" SET DATA TYPE text;
  ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'Other'::text;
  -- Hand-written: the admin role becomes the admin flag, and the job title becomes the role.
  ALTER TABLE "users" ADD COLUMN "is_admin" boolean DEFAULT false;
  UPDATE "users" SET "is_admin" = true WHERE "role" = 'admin';
  UPDATE "users" SET "role" = COALESCE("title"::text, CASE "role" WHEN 'viewer' THEN 'Commissioner' WHEN 'pengelola' THEN 'Staff' WHEN 'admin' THEN 'Lead' ELSE 'Other' END);
  DROP TYPE "public"."enum_users_role";
  CREATE TYPE "public"."enum_users_role" AS ENUM('Lead', 'Developer', 'Designer', 'Marketing', 'Business', 'Staff', 'Finance', 'Commissioner', 'Other');
  ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'Other'::"public"."enum_users_role";
  ALTER TABLE "users" ALTER COLUMN "role" SET DATA TYPE "public"."enum_users_role" USING "role"::"public"."enum_users_role";
  ALTER TABLE "permissions" ADD COLUMN "lead_view_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_edit_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_edit_clients" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_edit_orders" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_edit_projects" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_edit_vault" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_all_units" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "lead_seo" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "developer_view_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "developer_edit_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "developer_edit_clients" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "developer_edit_orders" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "developer_edit_projects" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "developer_edit_vault" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "developer_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "developer_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "developer_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_view_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_edit_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_edit_clients" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_edit_orders" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_edit_projects" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_edit_vault" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "designer_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "designer_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "marketing_view_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "marketing_edit_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "marketing_edit_clients" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "marketing_edit_orders" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "marketing_edit_projects" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "marketing_edit_vault" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "marketing_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "marketing_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "marketing_seo" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "business_view_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "business_edit_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "business_edit_clients" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "business_edit_orders" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "business_edit_projects" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "business_edit_vault" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "business_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "business_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "business_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "staff_view_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "staff_edit_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "staff_edit_clients" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "staff_edit_orders" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "staff_edit_projects" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "staff_edit_vault" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "staff_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "staff_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "staff_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "finance_view_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "finance_edit_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "finance_edit_clients" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "finance_edit_orders" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "finance_edit_projects" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "finance_edit_vault" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "finance_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "finance_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "finance_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_view_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_edit_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_edit_clients" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_edit_orders" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_edit_projects" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_edit_vault" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_team" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_all_units" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "commissioner_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_view_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_edit_money" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_edit_clients" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_edit_orders" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_edit_projects" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_edit_vault" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "other_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "other_seo" boolean DEFAULT false;
  ALTER TABLE "users" DROP COLUMN "title";
  ALTER TABLE "permissions" DROP COLUMN "pengelola_edit";
  ALTER TABLE "permissions" DROP COLUMN "pengelola_money";
  ALTER TABLE "permissions" DROP COLUMN "pengelola_team";
  ALTER TABLE "permissions" DROP COLUMN "pengelola_all_units";
  ALTER TABLE "permissions" DROP COLUMN "pengelola_seo";
  ALTER TABLE "permissions" DROP COLUMN "member_edit";
  ALTER TABLE "permissions" DROP COLUMN "member_money";
  ALTER TABLE "permissions" DROP COLUMN "member_team";
  ALTER TABLE "permissions" DROP COLUMN "member_all_units";
  ALTER TABLE "permissions" DROP COLUMN "member_seo";
  ALTER TABLE "permissions" DROP COLUMN "viewer_edit";
  ALTER TABLE "permissions" DROP COLUMN "viewer_money";
  ALTER TABLE "permissions" DROP COLUMN "viewer_team";
  ALTER TABLE "permissions" DROP COLUMN "viewer_all_units";
  ALTER TABLE "permissions" DROP COLUMN "viewer_seo";
  DROP TYPE "public"."enum_users_title";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_users_title" AS ENUM('Lead', 'Developer', 'Designer', 'Marketing', 'Business', 'Staff', 'Finance', 'Commissioner', 'Other');
  ALTER TABLE "users" ALTER COLUMN "role" SET DATA TYPE text;
  ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'member'::text;
  UPDATE "users" SET "role" = CASE WHEN "is_admin" THEN 'admin' WHEN "role" IN ('Staff', 'Finance') THEN 'pengelola' WHEN "role" = 'Commissioner' THEN 'viewer' ELSE 'member' END;
  DROP TYPE "public"."enum_users_role";
  CREATE TYPE "public"."enum_users_role" AS ENUM('admin', 'pengelola', 'member', 'viewer');
  ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'member'::"public"."enum_users_role";
  ALTER TABLE "users" ALTER COLUMN "role" SET DATA TYPE "public"."enum_users_role" USING "role"::"public"."enum_users_role";
  ALTER TABLE "users" ADD COLUMN "title" "enum_users_title";
  ALTER TABLE "permissions" ADD COLUMN "pengelola_edit" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "pengelola_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "pengelola_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "pengelola_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "pengelola_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "member_edit" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "member_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "member_team" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "member_all_units" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "member_seo" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "viewer_edit" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "viewer_money" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "viewer_team" boolean DEFAULT false;
  ALTER TABLE "permissions" ADD COLUMN "viewer_all_units" boolean DEFAULT true;
  ALTER TABLE "permissions" ADD COLUMN "viewer_seo" boolean DEFAULT false;
  ALTER TABLE "users" DROP COLUMN "is_admin";
  ALTER TABLE "permissions" DROP COLUMN "lead_view_money";
  ALTER TABLE "permissions" DROP COLUMN "lead_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "lead_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "lead_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "lead_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "lead_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "lead_team";
  ALTER TABLE "permissions" DROP COLUMN "lead_all_units";
  ALTER TABLE "permissions" DROP COLUMN "lead_seo";
  ALTER TABLE "permissions" DROP COLUMN "developer_view_money";
  ALTER TABLE "permissions" DROP COLUMN "developer_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "developer_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "developer_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "developer_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "developer_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "developer_team";
  ALTER TABLE "permissions" DROP COLUMN "developer_all_units";
  ALTER TABLE "permissions" DROP COLUMN "developer_seo";
  ALTER TABLE "permissions" DROP COLUMN "designer_view_money";
  ALTER TABLE "permissions" DROP COLUMN "designer_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "designer_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "designer_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "designer_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "designer_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "designer_team";
  ALTER TABLE "permissions" DROP COLUMN "designer_all_units";
  ALTER TABLE "permissions" DROP COLUMN "designer_seo";
  ALTER TABLE "permissions" DROP COLUMN "marketing_view_money";
  ALTER TABLE "permissions" DROP COLUMN "marketing_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "marketing_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "marketing_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "marketing_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "marketing_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "marketing_team";
  ALTER TABLE "permissions" DROP COLUMN "marketing_all_units";
  ALTER TABLE "permissions" DROP COLUMN "marketing_seo";
  ALTER TABLE "permissions" DROP COLUMN "business_view_money";
  ALTER TABLE "permissions" DROP COLUMN "business_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "business_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "business_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "business_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "business_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "business_team";
  ALTER TABLE "permissions" DROP COLUMN "business_all_units";
  ALTER TABLE "permissions" DROP COLUMN "business_seo";
  ALTER TABLE "permissions" DROP COLUMN "staff_view_money";
  ALTER TABLE "permissions" DROP COLUMN "staff_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "staff_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "staff_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "staff_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "staff_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "staff_team";
  ALTER TABLE "permissions" DROP COLUMN "staff_all_units";
  ALTER TABLE "permissions" DROP COLUMN "staff_seo";
  ALTER TABLE "permissions" DROP COLUMN "finance_view_money";
  ALTER TABLE "permissions" DROP COLUMN "finance_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "finance_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "finance_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "finance_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "finance_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "finance_team";
  ALTER TABLE "permissions" DROP COLUMN "finance_all_units";
  ALTER TABLE "permissions" DROP COLUMN "finance_seo";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_view_money";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_team";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_all_units";
  ALTER TABLE "permissions" DROP COLUMN "commissioner_seo";
  ALTER TABLE "permissions" DROP COLUMN "other_view_money";
  ALTER TABLE "permissions" DROP COLUMN "other_edit_money";
  ALTER TABLE "permissions" DROP COLUMN "other_edit_clients";
  ALTER TABLE "permissions" DROP COLUMN "other_edit_orders";
  ALTER TABLE "permissions" DROP COLUMN "other_edit_projects";
  ALTER TABLE "permissions" DROP COLUMN "other_edit_vault";
  ALTER TABLE "permissions" DROP COLUMN "other_team";
  ALTER TABLE "permissions" DROP COLUMN "other_all_units";
  ALTER TABLE "permissions" DROP COLUMN "other_seo";`)
}
