/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    clients: Client;
    orders: Order;
    projects: Project;
    documents: Document;
    transactions: Transaction;
    receipts: Receipt;
    prospects: Prospect;
    'vault-documents': VaultDocument;
    'vault-files': VaultFile;
    'ai-usage': AiUsage;
    'seo-audits': SeoAudit;
    events: HubEvent;
    'event-photos': EventPhoto;
    accounts: Account;
    activity: Activity;
    avatars: Avatar;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    clients: ClientsSelect<false> | ClientsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    receipts: ReceiptsSelect<false> | ReceiptsSelect<true>;
    prospects: ProspectsSelect<false> | ProspectsSelect<true>;
    'vault-documents': VaultDocumentsSelect<false> | VaultDocumentsSelect<true>;
    'vault-files': VaultFilesSelect<false> | VaultFilesSelect<true>;
    'ai-usage': AiUsageSelect<false> | AiUsageSelect<true>;
    'seo-audits': SeoAuditsSelect<false> | SeoAuditsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-photos': EventPhotosSelect<false> | EventPhotosSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    activity: ActivitySelect<false> | ActivitySelect<true>;
    avatars: AvatarsSelect<false> | AvatarsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    permissions: Permission;
    perintis: Perinti;
  };
  globalsSelect: {
    permissions: PermissionsSelect<false> | PermissionsSelect<true>;
    perintis: PerintisSelect<false> | PerintisSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  kind: 'usaha' | 'perorangan';
  name: string;
  owner?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  city?: string | null;
  businessType?: ('kuliner' | 'kesehatan' | 'jasa-lokal' | 'sekolah' | 'toko' | 'b2b' | 'industri' | 'lainnya') | null;
  package?: ('starter' | 'business' | 'premium' | 'custom') | null;
  annualFee?: number | null;
  startDate?: string | null;
  /**
   * Kosongkan untuk otomatis satu tahun setelah tanggal mulai.
   */
  renewalDate?: string | null;
  status: 'prospek' | 'aktif' | 'jatuh-tempo' | 'berhenti';
  links?: {
    website?: string | null;
    googleProfile?: string | null;
    instagram?: string | null;
  };
  supply?: {
    legalName?: string | null;
    npwp?: string | null;
    vendorNumber?: string | null;
    paymentTermsDays?: number | null;
    billingAddress?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  number: string;
  revision?: number | null;
  client: number | Client;
  buyerName?: string | null;
  buyerEmail?: string | null;
  orderDate: string;
  deliveryDate?: string | null;
  shipTo?: string | null;
  incoterm?: string | null;
  paymentTermsDays?: number | null;
  items?:
    | {
        material?: string | null;
        partNumber?: string | null;
        description: string;
        qty: number;
        uom?: string | null;
        unitPrice: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Dihitung dari item kalau ada item.
   */
  subtotal?: number | null;
  status: 'diterima' | 'sourcing' | 'dikirim' | 'ditagih' | 'dibayar' | 'batal';
  invoiceNumber?: string | null;
  invoiceDate?: string | null;
  dueDate?: string | null;
  documents?:
    | {
        kind: 'po' | 'invoice' | 'surat-jalan' | 'faktur-pajak' | 'bukti-bayar' | 'lainnya';
        file: number | Document;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  name: string;
  client: number | Client;
  stage: 'discovery' | 'scope' | 'kickoff' | 'desain' | 'build' | 'review' | 'launch' | 'selesai' | 'batal';
  health: 'lancar' | 'berisiko' | 'terhambat';
  owner?: (number | null) | User;
  stageChangedAt?: string | null;
  value?: number | null;
  dpPercent?: number | null;
  startDate?: string | null;
  targetDate?: string | null;
  nextAction?: string | null;
  nextActionAt?: string | null;
  /**
   * Biasanya sesuatu dari klien: aset, jawaban, pembayaran.
   */
  blocker?: string | null;
  brief?: {
    goals?: string | null;
    users?: string | null;
    currentFlow?: string | null;
    targetFlow?: string | null;
    successMeasure?: string | null;
    constraints?: string | null;
    /**
     * Aplikasi pembanding, standar atau metode, contoh laporan. Nama, tautan, satu baris pelajaran.
     */
    references?: string | null;
    confirmedAt?: string | null;
  };
  deliverables?:
    | {
        title: string;
        done?: boolean | null;
        doneAt?: string | null;
        id?: string | null;
      }[]
    | null;
  log?:
    | {
        date: string;
        type: 'pertemuan' | 'catatan' | 'keputusan' | 'perubahan' | 'klien' | 'tahap' | 'status';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        kind: 'brief' | 'presentasi' | 'scope' | 'invoice' | 'serah-terima' | 'lainnya';
        file: number | Document;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  links?: {
    repo?: string | null;
    staging?: string | null;
    live?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'Lead' | 'Developer' | 'Designer' | 'Marketing' | 'Business' | 'Staff' | 'Finance' | 'Commissioner' | 'Other';
  /**
   * Semua hak, kelola tim dan hak akses.
   */
  isAdmin?: boolean | null;
  /**
   * Ruang lingkup untuk peran tanpa hak Melihat semua unit.
   */
  units?: ('digital' | 'apps' | 'supply')[] | null;
  photo?: (number | null) | Avatar;
  /**
   * Supaya rekan bisa langsung menghubungi.
   */
  whatsapp?: string | null;
  /**
   * Satu kalimat: apa yang Anda pegang.
   */
  bio?: string | null;
  lastLoginAt?: string | null;
  lastSeenAt?: string | null;
  calendarToken?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars".
 */
export interface Avatar {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  date: string;
  type: 'masuk' | 'keluar';
  amount: number;
  category:
    | 'pembayaran-klien'
    | 'perpanjangan'
    | 'penjualan-barang'
    | 'pemasukan-lain'
    | 'setoran-modal'
    | 'pinjaman-diterima'
    | 'pembelian-barang'
    | 'logistik'
    | 'transportasi'
    | 'hosting-domain'
    | 'tools'
    | 'iklan'
    | 'gaji-honor'
    | 'operasional'
    | 'pajak'
    | 'lainnya'
    | 'pengembalian-pinjaman'
    | 'prive-dividen';
  method?: ('transfer' | 'qris' | 'tunai') | null;
  client?: (number | null) | Client;
  order?: (number | null) | Order;
  project?: (number | null) | Project;
  /**
   * Nomor invoice, nomor referensi transfer, atau keterangan singkat.
   */
  reference?: string | null;
  receipt?: (number | null) | Receipt;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts".
 */
export interface Receipt {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prospects".
 */
export interface Prospect {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  kind: 'usaha' | 'perorangan';
  company: string;
  sector?: ('tambang' | 'migas' | 'epc' | 'manufaktur' | 'distributor' | 'lainnya') | null;
  city?: string | null;
  source?: ('klien-lama' | 'referensi' | 'riset' | 'asosiasi' | 'linkedin' | 'lainnya') | null;
  website?: string | null;
  linkedin?: string | null;
  contacts?:
    | {
        name: string;
        role?: string | null;
        email?: string | null;
        phone?: string | null;
        linkedin?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Kapan terakhir kontak, dengan siapa, apa yang dipasok atau dibahas, hasilnya. Dipakai skill /outreach agar pesan membuka dengan pengingat yang spesifik.
   */
  history?: string | null;
  status: 'baru' | 'riset' | 'draf' | 'terkirim' | 'dibalas' | 'pertemuan' | 'klien' | 'berhenti';
  owner?: (number | null) | User;
  research?: string | null;
  researchedAt?: string | null;
  draftSubject?: string | null;
  draftChannel?: ('email' | 'whatsapp' | 'linkedin' | 'telepon' | 'pertemuan') | null;
  draft?: string | null;
  lastSentAt?: string | null;
  sentChannel?: ('email' | 'whatsapp' | 'linkedin' | 'telepon' | 'pertemuan') | null;
  nextFollowUpAt?: string | null;
  followUpCount?: number | null;
  repliedAt?: string | null;
  client?: (number | null) | Client;
  log?:
    | {
        date: string;
        type: 'riset' | 'draf' | 'kirim' | 'tindak-lanjut' | 'balasan' | 'catatan' | 'status';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-documents".
 */
export interface VaultDocument {
  id: number;
  title: string;
  category:
    | 'akta'
    | 'izin'
    | 'pajak'
    | 'sertifikat'
    | 'profil'
    | 'referensi'
    | 'identitas'
    | 'keuangan'
    | 'kontrak'
    | 'lainnya';
  number?: string | null;
  issuer?: string | null;
  issuedAt?: string | null;
  expiresAt?: string | null;
  file: number | VaultFile;
  /**
   * PNG kecil halaman pertama, dirender di browser saat unggah.
   */
  thumbnail?: (number | null) | VaultFile;
  /**
   * Hanya admin, finance, dan staf yang bisa melihat dan mengunduh.
   */
  confidential?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-files".
 */
export interface VaultFile {
  id: number;
  confidential?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage".
 */
export interface AiUsage {
  id: number;
  feature: 'po-import';
  model: string;
  unit: 'digital' | 'apps' | 'supply';
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  user?: (number | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits".
 */
export interface SeoAudit {
  id: number;
  path: string;
  url: string;
  fetchedAt: string;
  statusCode?: number | null;
  ttfbMs?: number | null;
  htmlBytes?: number | null;
  title?: string | null;
  description?: string | null;
  passed?: number | null;
  total?: number | null;
  checks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface HubEvent {
  id: number;
  title: string;
  kind: 'rapat-tim' | 'meeting-klien' | 'mentoring' | 'konten' | 'fokus' | 'lainnya';
  startAt: string;
  endAt?: string | null;
  location?: string | null;
  participants?: (number | User)[] | null;
  client?: (number | null) | Client;
  project?: (number | null) | Project;
  prospect?: (number | null) | Prospect;
  content?: {
    platform?: ('instagram' | 'threads' | 'linkedin' | 'facebook' | 'youtube' | 'tiktok' | 'x' | 'website') | null;
    status?: ('ide' | 'draf' | 'siap' | 'tayang') | null;
    designUrl?: string | null;
    postUrl?: string | null;
  };
  photo?: (number | null) | EventPhoto;
  agenda?: string | null;
  notes?: string | null;
  followUps?:
    | {
        text: string;
        owner?: (number | null) | User;
        dueAt?: string | null;
        doneAt?: string | null;
        id?: string | null;
      }[]
    | null;
  projectLogId?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-photos".
 */
export interface EventPhoto {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  platform:
    | 'whatsapp'
    | 'google-business'
    | 'instagram'
    | 'threads'
    | 'linkedin'
    | 'github'
    | 'facebook'
    | 'youtube'
    | 'tiktok'
    | 'x'
    | 'email'
    | 'domain'
    | 'hosting'
    | 'lainnya';
  status: 'belum' | 'aktif' | 'ditinggalkan';
  /**
   * Contoh: @zynergyid, admin@zynergy.co.id, zynergy.co.id
   */
  name: string;
  url?: string | null;
  holder?: (number | null) | User;
  loginEmail?: string | null;
  phone?: string | null;
  /**
   * Contoh: SMS ke HP kantor, Google Authenticator di HP Danish
   */
  twoFactor?: string | null;
  /**
   * Contoh: Bitwarden tim, brankas fisik.
   */
  passwordWhere?: string | null;
  visibility: 'tim' | 'rahasia';
  passwordEnc?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
  id: number;
  actor?: (number | null) | User;
  /**
   * Disimpan terpisah supaya tetap terbaca setelah akun dihapus.
   */
  actorName: string;
  action: 'create' | 'update' | 'delete' | 'login' | 'export' | 'view';
  collection: string;
  docId?: number | null;
  title: string;
  summary?: string | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  unit?: ('digital' | 'apps' | 'supply') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'receipts';
        value: number | Receipt;
      } | null)
    | ({
        relationTo: 'prospects';
        value: number | Prospect;
      } | null)
    | ({
        relationTo: 'vault-documents';
        value: number | VaultDocument;
      } | null)
    | ({
        relationTo: 'vault-files';
        value: number | VaultFile;
      } | null)
    | ({
        relationTo: 'ai-usage';
        value: number | AiUsage;
      } | null)
    | ({
        relationTo: 'seo-audits';
        value: number | SeoAudit;
      } | null)
    | ({
        relationTo: 'events';
        value: number | HubEvent;
      } | null)
    | ({
        relationTo: 'event-photos';
        value: number | EventPhoto;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'activity';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'avatars';
        value: number | Avatar;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  unit?: T;
  kind?: T;
  name?: T;
  owner?: T;
  whatsapp?: T;
  email?: T;
  city?: T;
  businessType?: T;
  package?: T;
  annualFee?: T;
  startDate?: T;
  renewalDate?: T;
  status?: T;
  links?:
    | T
    | {
        website?: T;
        googleProfile?: T;
        instagram?: T;
      };
  supply?:
    | T
    | {
        legalName?: T;
        npwp?: T;
        vendorNumber?: T;
        paymentTermsDays?: T;
        billingAddress?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  unit?: T;
  number?: T;
  revision?: T;
  client?: T;
  buyerName?: T;
  buyerEmail?: T;
  orderDate?: T;
  deliveryDate?: T;
  shipTo?: T;
  incoterm?: T;
  paymentTermsDays?: T;
  items?:
    | T
    | {
        material?: T;
        partNumber?: T;
        description?: T;
        qty?: T;
        uom?: T;
        unitPrice?: T;
        id?: T;
      };
  subtotal?: T;
  status?: T;
  invoiceNumber?: T;
  invoiceDate?: T;
  dueDate?: T;
  documents?:
    | T
    | {
        kind?: T;
        file?: T;
        note?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  unit?: T;
  name?: T;
  client?: T;
  stage?: T;
  health?: T;
  owner?: T;
  stageChangedAt?: T;
  value?: T;
  dpPercent?: T;
  startDate?: T;
  targetDate?: T;
  nextAction?: T;
  nextActionAt?: T;
  blocker?: T;
  brief?:
    | T
    | {
        goals?: T;
        users?: T;
        currentFlow?: T;
        targetFlow?: T;
        successMeasure?: T;
        constraints?: T;
        references?: T;
        confirmedAt?: T;
      };
  deliverables?:
    | T
    | {
        title?: T;
        done?: T;
        doneAt?: T;
        id?: T;
      };
  log?:
    | T
    | {
        date?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        kind?: T;
        file?: T;
        note?: T;
        id?: T;
      };
  links?:
    | T
    | {
        repo?: T;
        staging?: T;
        live?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  unit?: T;
  date?: T;
  type?: T;
  amount?: T;
  category?: T;
  method?: T;
  client?: T;
  order?: T;
  project?: T;
  reference?: T;
  receipt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts_select".
 */
export interface ReceiptsSelect<T extends boolean = true> {
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prospects_select".
 */
export interface ProspectsSelect<T extends boolean = true> {
  unit?: T;
  kind?: T;
  company?: T;
  sector?: T;
  city?: T;
  source?: T;
  website?: T;
  linkedin?: T;
  contacts?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
        phone?: T;
        linkedin?: T;
        id?: T;
      };
  history?: T;
  status?: T;
  owner?: T;
  research?: T;
  researchedAt?: T;
  draftSubject?: T;
  draftChannel?: T;
  draft?: T;
  lastSentAt?: T;
  sentChannel?: T;
  nextFollowUpAt?: T;
  followUpCount?: T;
  repliedAt?: T;
  client?: T;
  log?:
    | T
    | {
        date?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-documents_select".
 */
export interface VaultDocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  number?: T;
  issuer?: T;
  issuedAt?: T;
  expiresAt?: T;
  file?: T;
  thumbnail?: T;
  confidential?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-files_select".
 */
export interface VaultFilesSelect<T extends boolean = true> {
  confidential?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage_select".
 */
export interface AiUsageSelect<T extends boolean = true> {
  feature?: T;
  model?: T;
  unit?: T;
  inputTokens?: T;
  outputTokens?: T;
  costUsd?: T;
  user?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-audits_select".
 */
export interface SeoAuditsSelect<T extends boolean = true> {
  path?: T;
  url?: T;
  fetchedAt?: T;
  statusCode?: T;
  ttfbMs?: T;
  htmlBytes?: T;
  title?: T;
  description?: T;
  passed?: T;
  total?: T;
  checks?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  startAt?: T;
  endAt?: T;
  location?: T;
  participants?: T;
  client?: T;
  project?: T;
  prospect?: T;
  content?:
    | T
    | {
        platform?: T;
        status?: T;
        designUrl?: T;
        postUrl?: T;
      };
  photo?: T;
  agenda?: T;
  notes?: T;
  followUps?:
    | T
    | {
        text?: T;
        owner?: T;
        dueAt?: T;
        doneAt?: T;
        id?: T;
      };
  projectLogId?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-photos_select".
 */
export interface EventPhotosSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  platform?: T;
  status?: T;
  name?: T;
  url?: T;
  holder?: T;
  loginEmail?: T;
  phone?: T;
  twoFactor?: T;
  passwordWhere?: T;
  visibility?: T;
  passwordEnc?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
  actor?: T;
  actorName?: T;
  action?: T;
  collection?: T;
  docId?: T;
  title?: T;
  summary?: T;
  changes?: T;
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars_select".
 */
export interface AvatarsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isAdmin?: T;
  units?: T;
  photo?: T;
  whatsapp?: T;
  bio?: T;
  lastLoginAt?: T;
  lastSeenAt?: T;
  calendarToken?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions".
 */
export interface Permission {
  id: number;
  Lead?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Developer?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Designer?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Marketing?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Business?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Staff?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Finance?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Commissioner?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  Other?: {
    viewMoney?: boolean | null;
    editMoney?: boolean | null;
    editClients?: boolean | null;
    editOrders?: boolean | null;
    editProjects?: boolean | null;
    editVault?: boolean | null;
    team?: boolean | null;
    allUnits?: boolean | null;
    seo?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perintis".
 */
export interface Perinti {
  id: number;
  teamName?: string | null;
  businessName?: string | null;
  groupNumber?: number | null;
  leader?: string | null;
  unit?: ('digital' | 'apps' | 'supply' | 'semua') | null;
  reports?: {
    report1?: {
      targets?: {
        omzet?: number | null;
        biaya?: number | null;
        laba?: number | null;
        transaksi?: number | null;
        unit?: number | null;
        saldo?: number | null;
      };
      actualOverride?: {
        omzet?: number | null;
        biaya?: number | null;
        laba?: number | null;
        transaksi?: number | null;
        unit?: number | null;
        saldo?: number | null;
      };
      good?: string | null;
      problems?: string | null;
      actions?: string | null;
      next?: string | null;
      innovation?: string | null;
      submittedAt?: string | null;
    };
    report2?: {
      targets?: {
        omzet?: number | null;
        biaya?: number | null;
        laba?: number | null;
        transaksi?: number | null;
        unit?: number | null;
        saldo?: number | null;
      };
      actualOverride?: {
        omzet?: number | null;
        biaya?: number | null;
        laba?: number | null;
        transaksi?: number | null;
        unit?: number | null;
        saldo?: number | null;
      };
      good?: string | null;
      problems?: string | null;
      actions?: string | null;
      next?: string | null;
      innovation?: string | null;
      submittedAt?: string | null;
    };
    report3?: {
      targets?: {
        omzet?: number | null;
        biaya?: number | null;
        laba?: number | null;
        transaksi?: number | null;
        unit?: number | null;
        saldo?: number | null;
      };
      actualOverride?: {
        omzet?: number | null;
        biaya?: number | null;
        laba?: number | null;
        transaksi?: number | null;
        unit?: number | null;
        saldo?: number | null;
      };
      good?: string | null;
      problems?: string | null;
      actions?: string | null;
      next?: string | null;
      innovation?: string | null;
      submittedAt?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissions_select".
 */
export interface PermissionsSelect<T extends boolean = true> {
  Lead?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Developer?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Designer?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Marketing?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Business?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Staff?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Finance?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Commissioner?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  Other?:
    | T
    | {
        viewMoney?: T;
        editMoney?: T;
        editClients?: T;
        editOrders?: T;
        editProjects?: T;
        editVault?: T;
        team?: T;
        allUnits?: T;
        seo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perintis_select".
 */
export interface PerintisSelect<T extends boolean = true> {
  teamName?: T;
  businessName?: T;
  groupNumber?: T;
  leader?: T;
  unit?: T;
  reports?:
    | T
    | {
        report1?:
          | T
          | {
              targets?:
                | T
                | {
                    omzet?: T;
                    biaya?: T;
                    laba?: T;
                    transaksi?: T;
                    unit?: T;
                    saldo?: T;
                  };
              actualOverride?:
                | T
                | {
                    omzet?: T;
                    biaya?: T;
                    laba?: T;
                    transaksi?: T;
                    unit?: T;
                    saldo?: T;
                  };
              good?: T;
              problems?: T;
              actions?: T;
              next?: T;
              innovation?: T;
              submittedAt?: T;
            };
        report2?:
          | T
          | {
              targets?:
                | T
                | {
                    omzet?: T;
                    biaya?: T;
                    laba?: T;
                    transaksi?: T;
                    unit?: T;
                    saldo?: T;
                  };
              actualOverride?:
                | T
                | {
                    omzet?: T;
                    biaya?: T;
                    laba?: T;
                    transaksi?: T;
                    unit?: T;
                    saldo?: T;
                  };
              good?: T;
              problems?: T;
              actions?: T;
              next?: T;
              innovation?: T;
              submittedAt?: T;
            };
        report3?:
          | T
          | {
              targets?:
                | T
                | {
                    omzet?: T;
                    biaya?: T;
                    laba?: T;
                    transaksi?: T;
                    unit?: T;
                    saldo?: T;
                  };
              actualOverride?:
                | T
                | {
                    omzet?: T;
                    biaya?: T;
                    laba?: T;
                    transaksi?: T;
                    unit?: T;
                    saldo?: T;
                  };
              good?: T;
              problems?: T;
              actions?: T;
              next?: T;
              innovation?: T;
              submittedAt?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}