/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    clients: Client;
    orders: Order;
    projects: Project;
    documents: Document;
    transactions: Transaction;
    receipts: Receipt;
    prospects: Prospect;
    'vault-documents': VaultDocument;
    'vault-files': VaultFile;
    'ai-usage': AiUsage;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    clients: ClientsSelect<false> | ClientsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    receipts: ReceiptsSelect<false> | ReceiptsSelect<true>;
    prospects: ProspectsSelect<false> | ProspectsSelect<true>;
    'vault-documents': VaultDocumentsSelect<false> | VaultDocumentsSelect<true>;
    'vault-files': VaultFilesSelect<false> | VaultFilesSelect<true>;
    'ai-usage': AiUsageSelect<false> | AiUsageSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  name: string;
  owner?: string | null;
  whatsapp?: string | null;
  email?: string | null;
  city?: string | null;
  businessType?: ('kuliner' | 'kesehatan' | 'jasa-lokal' | 'sekolah' | 'toko' | 'b2b' | 'industri' | 'lainnya') | null;
  package?: ('starter' | 'business' | 'premium' | 'custom') | null;
  annualFee?: number | null;
  startDate?: string | null;
  /**
   * Kosongkan untuk otomatis satu tahun setelah tanggal mulai.
   */
  renewalDate?: string | null;
  status: 'prospek' | 'aktif' | 'jatuh-tempo' | 'berhenti';
  links?: {
    website?: string | null;
    googleProfile?: string | null;
    instagram?: string | null;
  };
  supply?: {
    legalName?: string | null;
    npwp?: string | null;
    vendorNumber?: string | null;
    paymentTermsDays?: number | null;
    billingAddress?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  number: string;
  revision?: number | null;
  client: number | Client;
  buyerName?: string | null;
  buyerEmail?: string | null;
  orderDate: string;
  deliveryDate?: string | null;
  shipTo?: string | null;
  incoterm?: string | null;
  paymentTermsDays?: number | null;
  items?:
    | {
        material?: string | null;
        partNumber?: string | null;
        description: string;
        qty: number;
        uom?: string | null;
        unitPrice: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Dihitung dari item kalau ada item.
   */
  subtotal?: number | null;
  status: 'diterima' | 'sourcing' | 'dikirim' | 'ditagih' | 'dibayar' | 'batal';
  invoiceNumber?: string | null;
  invoiceDate?: string | null;
  dueDate?: string | null;
  documents?:
    | {
        kind: 'po' | 'invoice' | 'surat-jalan' | 'faktur-pajak' | 'bukti-bayar' | 'lainnya';
        file: number | Document;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  name: string;
  client: number | Client;
  stage: 'discovery' | 'scope' | 'kickoff' | 'desain' | 'build' | 'review' | 'launch' | 'selesai' | 'batal';
  health: 'lancar' | 'berisiko' | 'terhambat';
  owner?: (number | null) | User;
  stageChangedAt?: string | null;
  value?: number | null;
  dpPercent?: number | null;
  startDate?: string | null;
  targetDate?: string | null;
  nextAction?: string | null;
  nextActionAt?: string | null;
  /**
   * Biasanya sesuatu dari klien: aset, jawaban, pembayaran.
   */
  blocker?: string | null;
  brief?: {
    goals?: string | null;
    users?: string | null;
    currentFlow?: string | null;
    targetFlow?: string | null;
    successMeasure?: string | null;
    constraints?: string | null;
    /**
     * Aplikasi pembanding, standar atau metode, contoh laporan. Nama, tautan, satu baris pelajaran.
     */
    references?: string | null;
    confirmedAt?: string | null;
  };
  deliverables?:
    | {
        title: string;
        done?: boolean | null;
        doneAt?: string | null;
        id?: string | null;
      }[]
    | null;
  log?:
    | {
        date: string;
        type: 'pertemuan' | 'catatan' | 'keputusan' | 'perubahan' | 'klien' | 'tahap' | 'status';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        kind: 'brief' | 'presentasi' | 'scope' | 'invoice' | 'serah-terima' | 'lainnya';
        file: number | Document;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  links?: {
    repo?: string | null;
    staging?: string | null;
    live?: string | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'finance' | 'staff' | 'member' | 'viewer';
  /**
   * Ruang lingkup finance dan anggota. Admin dan pengawas otomatis semua unit.
   */
  units?: ('digital' | 'apps' | 'supply')[] | null;
  title?:
    | ('Lead' | 'Developer' | 'Designer' | 'Marketing' | 'Business' | 'Staf' | 'Finance' | 'Komisaris' | 'Lainnya')
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  date: string;
  type: 'masuk' | 'keluar';
  amount: number;
  category:
    | 'pembayaran-klien'
    | 'perpanjangan'
    | 'penjualan-barang'
    | 'pemasukan-lain'
    | 'setoran-modal'
    | 'pinjaman-diterima'
    | 'pembelian-barang'
    | 'logistik'
    | 'transportasi'
    | 'hosting-domain'
    | 'tools'
    | 'iklan'
    | 'gaji-honor'
    | 'operasional'
    | 'pajak'
    | 'lainnya'
    | 'pengembalian-pinjaman'
    | 'prive-dividen';
  method?: ('transfer' | 'qris' | 'tunai') | null;
  client?: (number | null) | Client;
  order?: (number | null) | Order;
  project?: (number | null) | Project;
  /**
   * Nomor invoice, nomor referensi transfer, atau keterangan singkat.
   */
  reference?: string | null;
  receipt?: (number | null) | Receipt;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts".
 */
export interface Receipt {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prospects".
 */
export interface Prospect {
  id: number;
  unit: 'digital' | 'apps' | 'supply';
  company: string;
  sector?: ('tambang' | 'migas' | 'epc' | 'manufaktur' | 'distributor' | 'lainnya') | null;
  city?: string | null;
  source?: ('klien-lama' | 'referensi' | 'riset' | 'asosiasi' | 'linkedin' | 'lainnya') | null;
  website?: string | null;
  linkedin?: string | null;
  contacts?:
    | {
        name: string;
        role?: string | null;
        email?: string | null;
        phone?: string | null;
        linkedin?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Kapan terakhir kontak, dengan siapa, apa yang dipasok atau dibahas, hasilnya. Dipakai skill /outreach agar pesan membuka dengan pengingat yang spesifik.
   */
  history?: string | null;
  status: 'baru' | 'riset' | 'draf' | 'terkirim' | 'dibalas' | 'pertemuan' | 'klien' | 'berhenti';
  owner?: (number | null) | User;
  research?: string | null;
  researchedAt?: string | null;
  draftSubject?: string | null;
  draftChannel?: ('email' | 'whatsapp' | 'linkedin' | 'telepon' | 'pertemuan') | null;
  draft?: string | null;
  lastSentAt?: string | null;
  sentChannel?: ('email' | 'whatsapp' | 'linkedin' | 'telepon' | 'pertemuan') | null;
  nextFollowUpAt?: string | null;
  followUpCount?: number | null;
  repliedAt?: string | null;
  client?: (number | null) | Client;
  log?:
    | {
        date: string;
        type: 'riset' | 'draf' | 'kirim' | 'tindak-lanjut' | 'balasan' | 'catatan' | 'status';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-documents".
 */
export interface VaultDocument {
  id: number;
  title: string;
  category:
    | 'akta'
    | 'izin'
    | 'pajak'
    | 'sertifikat'
    | 'profil'
    | 'referensi'
    | 'identitas'
    | 'keuangan'
    | 'kontrak'
    | 'lainnya';
  number?: string | null;
  issuer?: string | null;
  issuedAt?: string | null;
  expiresAt?: string | null;
  file: number | VaultFile;
  /**
   * PNG kecil halaman pertama, dirender di browser saat unggah.
   */
  thumbnail?: (number | null) | VaultFile;
  /**
   * Hanya admin, finance, dan staf yang bisa melihat dan mengunduh.
   */
  confidential?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-files".
 */
export interface VaultFile {
  id: number;
  confidential?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage".
 */
export interface AiUsage {
  id: number;
  feature: 'po-import';
  model: string;
  unit: 'digital' | 'apps' | 'supply';
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  user?: (number | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'receipts';
        value: number | Receipt;
      } | null)
    | ({
        relationTo: 'prospects';
        value: number | Prospect;
      } | null)
    | ({
        relationTo: 'vault-documents';
        value: number | VaultDocument;
      } | null)
    | ({
        relationTo: 'vault-files';
        value: number | VaultFile;
      } | null)
    | ({
        relationTo: 'ai-usage';
        value: number | AiUsage;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  unit?: T;
  name?: T;
  owner?: T;
  whatsapp?: T;
  email?: T;
  city?: T;
  businessType?: T;
  package?: T;
  annualFee?: T;
  startDate?: T;
  renewalDate?: T;
  status?: T;
  links?:
    | T
    | {
        website?: T;
        googleProfile?: T;
        instagram?: T;
      };
  supply?:
    | T
    | {
        legalName?: T;
        npwp?: T;
        vendorNumber?: T;
        paymentTermsDays?: T;
        billingAddress?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  unit?: T;
  number?: T;
  revision?: T;
  client?: T;
  buyerName?: T;
  buyerEmail?: T;
  orderDate?: T;
  deliveryDate?: T;
  shipTo?: T;
  incoterm?: T;
  paymentTermsDays?: T;
  items?:
    | T
    | {
        material?: T;
        partNumber?: T;
        description?: T;
        qty?: T;
        uom?: T;
        unitPrice?: T;
        id?: T;
      };
  subtotal?: T;
  status?: T;
  invoiceNumber?: T;
  invoiceDate?: T;
  dueDate?: T;
  documents?:
    | T
    | {
        kind?: T;
        file?: T;
        note?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  unit?: T;
  name?: T;
  client?: T;
  stage?: T;
  health?: T;
  owner?: T;
  stageChangedAt?: T;
  value?: T;
  dpPercent?: T;
  startDate?: T;
  targetDate?: T;
  nextAction?: T;
  nextActionAt?: T;
  blocker?: T;
  brief?:
    | T
    | {
        goals?: T;
        users?: T;
        currentFlow?: T;
        targetFlow?: T;
        successMeasure?: T;
        constraints?: T;
        references?: T;
        confirmedAt?: T;
      };
  deliverables?:
    | T
    | {
        title?: T;
        done?: T;
        doneAt?: T;
        id?: T;
      };
  log?:
    | T
    | {
        date?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        kind?: T;
        file?: T;
        note?: T;
        id?: T;
      };
  links?:
    | T
    | {
        repo?: T;
        staging?: T;
        live?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  unit?: T;
  date?: T;
  type?: T;
  amount?: T;
  category?: T;
  method?: T;
  client?: T;
  order?: T;
  project?: T;
  reference?: T;
  receipt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts_select".
 */
export interface ReceiptsSelect<T extends boolean = true> {
  unit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prospects_select".
 */
export interface ProspectsSelect<T extends boolean = true> {
  unit?: T;
  company?: T;
  sector?: T;
  city?: T;
  source?: T;
  website?: T;
  linkedin?: T;
  contacts?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
        phone?: T;
        linkedin?: T;
        id?: T;
      };
  history?: T;
  status?: T;
  owner?: T;
  research?: T;
  researchedAt?: T;
  draftSubject?: T;
  draftChannel?: T;
  draft?: T;
  lastSentAt?: T;
  sentChannel?: T;
  nextFollowUpAt?: T;
  followUpCount?: T;
  repliedAt?: T;
  client?: T;
  log?:
    | T
    | {
        date?: T;
        type?: T;
        note?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-documents_select".
 */
export interface VaultDocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  number?: T;
  issuer?: T;
  issuedAt?: T;
  expiresAt?: T;
  file?: T;
  thumbnail?: T;
  confidential?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vault-files_select".
 */
export interface VaultFilesSelect<T extends boolean = true> {
  confidential?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage_select".
 */
export interface AiUsageSelect<T extends boolean = true> {
  feature?: T;
  model?: T;
  unit?: T;
  inputTokens?: T;
  outputTokens?: T;
  costUsd?: T;
  user?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  units?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}